version: "3"

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py create_user &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASS=pgpassword
      - SLACK_WEBHOOK=https://hooks.slack.com/services/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
      - ADMN_USER=admin@zebrands.com
      - ADMN_PASS=admin
      - ADMN_NAME=Default Admin User
    depends_on:
      - db
  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pgpassword