# Generated by Django 3.2.4 on 2021-06-03 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_is_admin_user_is_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('price', models.FloatField(default=0)),
                ('brand', models.CharField(max_length=200)),
            ],
        ),
    ]
